### ISSUE TITLE
Change a element based on the theme mode

### ISSUE THREAD

**Issue by safiullahahamed** [maheshbosctechlabs/day_night_theme_flutter#8]
How can we change a element based on the theme mode?
For example: 
An image should change based on the theme. If it is dark mode, show a dark image else show default image.

**Comment by varunkamani** [comment]
You can create a variable like this`bool isLightTheme  = Theme.of(context).brightness == Brightness.light;` to get the current theme. Base on the value of `isLightTheme` you can show the image.
